name: Ubuntu CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          lfs: true
          clean: true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install g++ cmake protobuf-compiler libprotobuf-dev -y

      - name: Configure
        run: |
          cmake -S . -B build -DUNIT_TESTING=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j"$(nproc)"

      - name: Test
        run: ctest --test-dir build --output-on-failure --verbose

      - name: Create package
        run: cpack --config build/CPackConfig.cmake

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: fenris-package
          path: build/*.tar.gz
